### ISSUE TITLE
Unreachable very useful code

### ISSUE THREAD

**Issue by HoustonBass** [urbanairship/connect-python-library#7]
https://github.com/urbanairship/connect-python-library/blob/140fd9d23d300c316d1525bbee7e4f1b292bf075/uaconnect/consumer.py#L373

Hey, so i recently built a consumer to read your compliance stream. 
And I setup my redis instance correctly, which I was under the impression, if I gave the consumer a recorder, it could read the offset _from_ the recorder. Which your code says it totally can...except thats not true, this feature has been refactored out of existence. 

Can you please fix this big ifelse so that the recorder can provide a resume offset?
btw, the whole block is here. The issue is the two lines proceeding the one where the offset is read from the recorder are mutually exclusive so one of them always gets run.
https://github.com/urbanairship/connect-python-library/blob/140fd9d23d300c316d1525bbee7e4f1b292bf075/uaconnect/consumer.py#L359-L373

**Comment by aschuman0** [comment]
Hi @HoustonBass - sorry for the issue. I'm looking at this fix now and will drop a note here when I push a patch.

**Comment by aschuman0** [comment]
@HoustonBass - This is fixed in v1.0.1 which is available in this repo and on pypi. You should be able to pick up the Recorder's offset passing no args to `Consumer.connect()`
Please let us know if there are any further issues.

**Comment by HoustonBass** [comment]
Hey, thanks for the update. 
It still doesn't work because if omitted a "if start is not null and start not in possible_start_values" on line 366
When start is null, the expression, "start not in possible_start_values" is true, so you still can't reach this code

```python
if start and resume_offset:
        logging.error("Request can only have start or resume_offset parameter")
        raise InvalidParametersError
elif not start and not resume_offset:
        logging.info(
                "Neither start nor resume_offset was provided. Attempting to read offset from recorder."
        )
        self.offset = self.recorder.read_offset()
elif start not in possible_start_values:
        logging.error("Start can only be one of EARLIEST or LATEST")
        raise InvalidParametersError
elif start in possible_start_values:
        self.start = start
elif resume_offset:
        self.offset = resume_offset
 ```

or splitting the sections logically

```python
if start:
    if resume_offset:
        logging.error("Request can only have start or resume_offset parameter")
        raise InvalidParametersError
    elif start not in possible_start_values:
        logging.error("Start can only be one of EARLIEST or LATEST")
        raise InvalidParametersError
    elif start in possible_start_values: #this becomes redundant now and can be reduced to else
        self.start = start
elif resume_offset:
        self.offset = resume_offset
else:
    logging.info(
            "Neither start nor resume_offset was provided. Attempting to read offset from recorder."
    )
    self.offset = self.recorder.read_offset()

 ```

if you wanted to keep consistency with you start and offset not both being passed you could move the 'offset and start' to before all this, i like that the best since its the most clearly readable albeit redudant 
```python
if start and resume_offset:
        logging.error("Request can only have start or resume_offset parameter")
        raise InvalidParametersError
elif start:
   if start not in possible_start_values:
        logging.error("Start can only be one of EARLIEST or LATEST")
        raise InvalidParametersError
    else:
        self.start = start
elif resume_offset:
        self.offset = resume_offset
else:
    logging.info(
            "Neither start nor resume_offset was provided. Attempting to read offset from recorder."
    )
    self.offset = self.recorder.read_offset()

```

**Comment by aschuman0** [comment]
This should be fixed in version 1.0.2 in this repo and on pypi. Please let us know if any issues remain. Thanks!
